# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8674e45ce2bd7ffa6ca8415fca47545df090261f0744ef78d29c39b9c41e921e0270940e38edad79fda27ae920c9e7c5493bc7818e5e82b1608b03d8fb7a160a

test:
  secret_key_base: 6bd7838a93e734742db86da969fa6b994f7bdcc8bac4c1bf1d8cb9cc80f4a8fc19d5674ec189f029e9b5581798f0c161c4e7edc62f1dea9f775736eea5f2edbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
